name: FirOnlineTime
version: '${version}'
main: top.catnies.firOnlineTime.FirOnlineTime
api-version: '1.18'
folia-supported: true
softdepend:
  - PlaceholderAPI
libraries:
  - com.zaxxer:HikariCP:5.1.0