# Database Configuration

MySQL:
  jdbc-url: "jdbc:mysql://127.0.0.1:3306/minecraft?useSSL=false&autoReconnect=true"
  jdbc-class: "com.mysql.cj.jdbc.Driver"
  properties:
    user: "catnies"
    password: "minato"